---
Standards:
  -
    Title: Intro to Git
    Description: "Intro to Git,  Git setup with Access Token, Git Workflow Setup, Commits"
    UID: 37ec02c8-be30-43d4-9d9b-af37e7bb7ff7
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: qCKw66
        Path: /git-setup/intro-to-git-vocab-and-concepts.md
      -
        Type: Resource
        UID: 610bc189-6b6b-4b35-b3af-1bc9ca4348bc
        Path: /git-setup/github-with-ssh.md
      -
        Type: Lesson
        UID: 6c114fa6
        Path: /git-setup/github-setup-with-access-token.md
      -
        Type: Lesson
        UID: EgvjDl
        Path: /git-setup/git-workflow-setup.md
      -
        Type: Lesson
        UID: CltvdV
        Path: /git-setup/commits.md
  -
    Title: "Managing Packages"
    Description: "Packages and Managing Packages, Virtual Environments"
    UID: 1e053af0-420f-48d6-bcbd-b3edbb822879
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: abirop
        Path: /managing-packages/packages-and-managing-packages.md
      -
        Type: Lesson
        UID: UZp4J5
        Path: /managing-packages/virtual-environments-and-projects.md
  -
    Title: Using The Debugger
    Description: "Intro to Debuggers, VS Code Debugging, Debugging Pytest, Problem Set: Using Debugger"
    UID: eb702636-a782-4ed3-8fb5-daca0aea5206
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: 26f0b589-cb0f-4539-a4a6-1cb64f9ee28b
        Path: /intermediate-python-debugging/intro-to-debuggers.md
      -
        Type: Lesson
        UID: 506303a8-2fab-4283-98b3-9b4576721620
        Path: /intermediate-python-debugging/debugging-with-vs-code.md
      -
        Type: Lesson
        UID: 0cf83e0c-4483-4a15-8713-f35c425a16e1
        Path: /intermediate-python-debugging/debugging-with-pytest.md
      -
        Type: Lesson
        UID: a8e761cc-0d1f-49f9-a80a-6d2f79579a04
        Path: /intermediate-python-debugging/problem-set-using-the-debugger.md
  -
    Title: Collaborating with Git
    Description: "Collaborating, Reviewing Git History, Git Cheatsheet, Problem Set: Git Commands, Activity: Git Collaboration"
    UID: DaSCfO
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: 1763bf75
        Path: /intro-to-git/activity-git-collaboration.instructor.md
      -
        Type: Lesson
        UID: wGkqyQ
        Path: /intro-to-git/collaborating.md
      -
        Type: Lesson
        UID: w3WLGs
        Path: /intro-to-git/reviewing-git-history.md
      -
        Type: Lesson
        UID: ce6c935d-a665-420e-97ba-8b4a5cebf4d7
        Path: /intro-to-git/git-cheatsheet.md
      -
        Type: Lesson
        UID: g1zQGU
        Path: /intro-to-git/problem-set-git-commands.md
      -
        Type: Lesson
        UID: 500d9781
        Path: /intro-to-git/activity-git-collaboration.md
      -
        Type: Resource
        UID: tSg96d
        Path: /intro-to-git/activity-git-history.md
  -
    Title: Code Coverage
    Description: "Activity: Code Coverage"
    UID: 58c95a4e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: d1ede537-7930-4f83-9b13-2263081b3b2d
        Path: /code-coverage/activity-code-coverage.instructor.md  
      -
        Type: Lesson
        UID: 29c5d18e-7412-4bb3-aa03-dd24137cfe16
        Path: /code-coverage/activity-code-coverage.md  
  -
    Title: Branches In Git
    Description: "Branches, Using Branches in Git, Problem Set: Git, Activity: Merge Carnival"
    UID: 76a4001e9bc2734c2e93ede4b8f1297e
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Instructor
        UID: bfe2e5a6-7731-44a5-9beb-e7b0e387954e
        Path: /branches-in-git/activity-merge-carnival.instructor.md
      -
        Type: Lesson
        UID: 6c8aa01cc55f51f3cb90f1fd9f851595
        Path: /branches-in-git/branches.md
      -
        Type: Lesson
        UID: f88500a61648d8752735ca1b0b3e9522
        Path: /branches-in-git/using-branches-in-git.md
      -
        Type: Lesson
        UID: a23c8692ae7b601177cd574151717d51
        Path: /branches-in-git/problem-set-git.md
      -
        Type: Lesson
        UID: c421363b-ef64-4017-9e90-25ca0ba14f79
        Path: /branches-in-git/activity-merge-carnival.md
  -
    Title: "External Resources"
    Description: "Learning Resources Provided by the Ada Community"
    UID: 19d7c672-ae13-407d-9cf2-d0615e75a726
    SuccessCriteria:
      - success criteria
    ContentFiles:
      -
        Type: Lesson
        UID: b928006a
        Path: /resources/external-resources.md